### ISSUE TITLE
你好，请问是修改了什么地方解决了OOM问题呢

### ISSUE THREAD

**Issue by lfxx** [yeyupiaoling/PaddlePaddle-DeepSpeech#10]
显存一直飙升，到最后就会出错

**Comment by yeyupiaoling** [comment]
原项目音频数据是从短到长排序的，所以后面训练的音频长度会越来越长，所以就出现了占用显存越来越大的情况。我这个项目是倒过来的，是音频长度是从长到短的，所以一开始训练不通过，你就设置更小的音频长度。参数里面可以设置的。



---原始邮件---
发件人: "高峰"<notifications@github.com&gt;
发送时间: 2021年2月8日(周一) 晚上6:10
收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] 你好，请问是修改了什么地方解决了OOM问题呢 (#10)




 
显存一直飙升，到最后就会出错

**Comment by lfxx** [comment]
> 原项目音频数据是从短到长排序的，所以后面训练的音频长度会越来越长，所以就出现了占用显存越来越大的情况。我这个项目是倒过来的，是音频长度是从长到短的，所以一开始训练不通过，你就设置更小的音频长度。参数里面可以设置的。
> […](#)
> ---原始邮件--- 发件人: "高峰"<notifications@github.com&gt; 发送时间: 2021年2月8日(周一) 晚上6:10 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] 你好，请问是修改了什么地方解决了OOM问题呢 (#10) 显存一直飙升，到最后就会出错 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

就是说单纯降低batch_size是没用的吗，需要降低音频长度

**Comment by yeyupiaoling** [comment]
是的，按照我的参数设定，12局显存是够的。



---原始邮件---
发件人: "高峰"<notifications@github.com&gt;
发送时间: 2021年2月8日(周一) 晚上6:51
收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;;
抄送: "夜雨飘零"<yeyupiaoling@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] 你好，请问是修改了什么地方解决了OOM问题呢 (#10)




  
原项目音频数据是从短到长排序的，所以后面训练的音频长度会越来越长，所以就出现了占用显存越来越大的情况。我这个项目是倒过来的，是音频长度是从长到短的，所以一开始训练不通过，你就设置更小的音频长度。参数里面可以设置的。
 …
 ---原始邮件--- 发件人: "高峰"<notifications@github.com&gt; 发送时间: 2021年2月8日(周一) 晚上6:10 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] 你好，请问是修改了什么地方解决了OOM问题呢 (#10) 显存一直飙升，到最后就会出错 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
就是说单纯降低batch_size是没用的吗，需要降低音频长度

**Comment by lfxx** [comment]
好的，非常感谢!
