### ISSUE TITLE
python tools/tune.py卡了很长时间不动

### ISSUE THREAD

**Issue by lfxx** [yeyupiaoling/PaddlePaddle-DeepSpeech#11]
如题，运行程序后，卡在
`finish initing model from pretrained params from .checkpoints/step_final`不动，卡了很长时间，这是正常的吗

**Comment by yeyupiaoling** [comment]
这是正常的，你看一下源码就知道，里面要做大量的推理。只是你可以跳过这部分，直接用默认参数，大多数情况下默认参数的效果还是比较好的。



---原始邮件---
发件人: "高峰"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 中午11:46
收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11)




 
如题，运行程序后，卡在
 finish initing model from pretrained params from .checkpoints/step_final不动，卡了很长时间，这是正常的吗

**Comment by lfxx** [comment]
但是并没有看到cpu和gpu有占用率，就一直在这儿卡着，也没有输出，感觉好奇怪



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夜雨飘零 <notifications@github.com&gt;
发送时间: 2021年2月9日 11:57
收件人: yeyupiaoling/PaddlePaddle-DeepSpeech <PaddlePaddle-DeepSpeech@noreply.github.com&gt;
抄送: 高峰 <1213117298@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11)





 这是正常的，你看一下源码就知道，里面要做大量的推理。只是你可以跳过这部分，直接用默认参数，大多数情况下默认参数的效果还是比较好的。 
 
 
 
 ---原始邮件--- 
 发件人: "高峰"<notifications@github.com&amp;gt; 
 发送时间: 2021年2月9日(周二) 中午11:46 
 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 
 
 
 
 
   
 如题，运行程序后，卡在 
  finish initing model from pretrained params from .checkpoints/step_final不动，卡了很长时间，这是正常的吗

**Comment by yeyupiaoling** [comment]
这样就不应该了



---原始邮件---
发件人: "高峰"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 中午11:59
收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;;
抄送: "夜雨飘零"<yeyupiaoling@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11)




 但是并没有看到cpu和gpu有占用率，就一直在这儿卡着，也没有输出，感觉好奇怪 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 夜雨飘零 <notifications@github.com&amp;gt; 
 发送时间: 2021年2月9日 11:57 
 收件人: yeyupiaoling/PaddlePaddle-DeepSpeech <PaddlePaddle-DeepSpeech@noreply.github.com&amp;gt; 
 抄送: 高峰 <1213117298@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 
 
 
 
 
 
  这是正常的，你看一下源码就知道，里面要做大量的推理。只是你可以跳过这部分，直接用默认参数，大多数情况下默认参数的效果还是比较好的。  
   
   
   
  ---原始邮件---  
  发件人: "高峰"<notifications@github.com&amp;amp;gt;  
  发送时间: 2021年2月9日(周二) 中午11:46  
  收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&amp;amp;gt;;  
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11)  
   
   
   
   
     
  如题，运行程序后，卡在  
   finish initing model from pretrained params from .checkpoints/step_final不动，卡了很长时间，这是正常的吗

**Comment by lfxx** [comment]
> 这样就不应该了
> […](#)
> ---原始邮件--- 发件人: "高峰"<notifications@github.com&gt; 发送时间: 2021年2月9日(周二) 中午11:59 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;; 抄送: "夜雨飘零"<yeyupiaoling@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 但是并没有看到cpu和gpu有占用率，就一直在这儿卡着，也没有输出，感觉好奇怪 发自我的iPhone
> ------------------ 原始邮件 ------------------ 发件人: 夜雨飘零 <notifications@github.com&amp;gt; 发送时间: 2021年2月9日 11:57 收件人: yeyupiaoling/PaddlePaddle-DeepSpeech <PaddlePaddle-DeepSpeech@noreply.github.com&amp;gt; 抄送: 高峰 <1213117298@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 主题: 回复：[yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 这是正常的，你看一下源码就知道，里面要做大量的推理。只是你可以跳过这部分，直接用默认参数，大多数情况下默认参数的效果还是比较好的。
> ---原始邮件--- 发件人: "高峰"<notifications@github.com&amp;amp;gt; 发送时间: 2021年2月9日(周二) 中午11:46 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&amp;amp;gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;; 主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 如题，运行程序后，卡在 finish initing model from pretrained params from .checkpoints/step_final不动，卡了很长时间，这是正常的吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

看了一下，其实还是在处理的，只不过速度很慢。另外想请教个问题，我手里有单声道和双声道的16000HZ音频，可以把他们混在一起训练吗，不知道声道数对于训练效果有没有影响

**Comment by yeyupiaoling** [comment]
你看一下源码，我的数据预处理有一部分代码是注释掉的，那个代码就是把全部其他不同频率的都转成单通道1600赫兹。



---原始邮件---
发件人: "高峰"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 下午2:47
收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;;
抄送: "夜雨飘零"<yeyupiaoling@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11)




  
这样就不应该了
 …
 ---原始邮件--- 发件人: "高峰"<notifications@github.com&gt; 发送时间: 2021年2月9日(周二) 中午11:59 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&gt;; 抄送: "夜雨飘零"<yeyupiaoling@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 但是并没有看到cpu和gpu有占用率，就一直在这儿卡着，也没有输出，感觉好奇怪 发自我的iPhone
 ------------------ 原始邮件 ------------------ 发件人: 夜雨飘零 <notifications@github.com&amp;gt; 发送时间: 2021年2月9日 11:57 收件人: yeyupiaoling/PaddlePaddle-DeepSpeech <PaddlePaddle-DeepSpeech@noreply.github.com&amp;gt; 抄送: 高峰 <1213117298@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 主题: 回复：[yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 这是正常的，你看一下源码就知道，里面要做大量的推理。只是你可以跳过这部分，直接用默认参数，大多数情况下默认参数的效果还是比较好的。
 ---原始邮件--- 发件人: "高峰"<notifications@github.com&amp;amp;gt; 发送时间: 2021年2月9日(周二) 中午11:46 收件人: "yeyupiaoling/PaddlePaddle-DeepSpeech"<PaddlePaddle-DeepSpeech@noreply.github.com&amp;amp;gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;; 主题: [yeyupiaoling/PaddlePaddle-DeepSpeech] python tools/tune.py卡了很长时间不动 (#11) 如题，运行程序后，卡在 finish initing model from pretrained params from .checkpoints/step_final不动，卡了很长时间，这是正常的吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看了一下，其实还是在处理的，只不过速度很慢。另外想请教个问题，我手里有单声道和双声道的16000HZ音频，可以把他们混在一起训练吗，不知道声道数对于训练效果有没有影响

**Comment by yeyupiaoling** [comment]
@lfxx 我优化了一下代码，速度快了超多，同时支持了Python3

**Comment by lfxx** [comment]
> @lfxx 我优化了一下代码，速度快了超多，同时支持了Python3

好的谢谢
